### ISSUE TITLE
Red neuronal 

### ISSUE THREAD

**Issue by Hugegar** [ManchesterRoboticsLtd/TE3002B_Intelligent_Robotics_Implementation#13]
Estamos intenado correr un modelo .h5 en la jetson con el ambiente de python 3, pero a la hora de correr el código con ese modelo nos marca errores en las depencias con CvBridge.

**Comment by Karen-Rdz** [comment]
Hola! En un nodo estamos suscribiéndonos al tópico de la cámara y utilizando la clase detector que se nos proporcionó en python 3, pero igual nos marca errores en CvBridge.

**Comment by MarcFacerias** [comment]
Si en python3 cv bridge no esta disponible. En la actividad 1 tenies un ejemplo de una funcion escrita con numpy que hace possible ese puente sin cv_bridge.
