### ISSUE TITLE
Compatibilidad red

### ISSUE THREAD

**Issue by A01745913** [ManchesterRoboticsLtd/TE3002B_Intelligent_Robotics_Implementation#18]
Se está intentando hacer uso de la red neuronal en la Jetson, sin embargo, muestra un problema de compatibilidad entre python 3, usado por tensorflow, y python 2, usado por el resto de Ros.

En este caso, como se puede proceder?

**Comment by MarcFacerias** [comment]
python2 y python3 pueden compartir topicos en la misma red de ros. Estrictamente hablando es un feature que ros no soporta en esta version en la practica si funciona. Solo tenies que ir con cuidado con cv_bridge, en la actividad 1 hay una funcion basada en numpy que permite hacer ese puente
