### ISSUE TITLE
Video seguidor de líneas 

### ISSUE THREAD

**Issue by Hugegar** [ManchesterRoboticsLtd/TE3002B_Intelligent_Robotics_Implementation#2]
Hola Mario, 
¿Donde se encuetra el video que nos dejaste de tarea para este jueves?

**Comment by mariomartinezgro** [comment]
Hola, 
Esta en la descripcion de la semana 6. Aqui te dejo el link
[Line Following](https://www.youtube.com/watch?v=Ah8C9yeG8Eg)
