### ISSUE TITLE
Demos de Ros_deep_learning no funcionan

### ISSUE THREAD

**Issue by SaulA01745146** [ManchesterRoboticsLtd/TE3002B_Intelligent_Robotics_Implementation#33]
Hemos tratado de correr algunas demos que ya tiene el repositorio de Ros_deep_learning, en específico el modelo de prueba de detectnet para intentar basarnos en eso para el funcionamiento de la red. El problema es que al momento de correr el launch, nos marca que no puede cargar el modelo de detectnet. ¿Saben cómo podemos arreglar esto? y si podemos arreglarlo ¿Cómo podemos cargar un modelo onnx personalizado?

**Comment by MarcFacerias** [comment]
A priori diria que si no encuentra el modelo de detecnet es por que no se descargo al instalar el package de ros_deep_learning. Puedes seguir estas instrucciones https://github.com/dusty-nv/jetson-inference/blob/master/docs/building-repo-2.md para reinstalar jetson_inference, solo asegurate de no instalar pytorch otra vez. Respecto a usar tu propio model onnx siempre que este tenga la misma arquitectura que el modelo detecnet puedes usar el template de la actividad 2 para hacer la inferencia
